version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "ml"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "..:/opt/ml_service"
    environment:
      MONGO_DSN: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:

volumes:
  mongodata:
