version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "ml"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "..:/opt/service"
    environment:
      MONGO_DSN: ""
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
